builders:
  tomlBuilder:
    import: "package:coolbox/builder/builder.dart"
    builder_factories: ["dataClassBuilder"]
    build_extensions: {".dart": [".data.dart"]}
    build_to: source
    auto_apply: root_package
